vatrate_index:
    path:     /
    defaults: { _controller: "AppBundle:VatRate:index" }
    methods:  GET

vatrate_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:VatRate:show" }
    methods:  GET

vatrate_new:
    path:     /new
    defaults: { _controller: "AppBundle:VatRate:new" }
    methods:  [GET, POST]

vatrate_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:VatRate:edit" }
    methods:  [GET, POST]

vatrate_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:VatRate:delete" }
    methods:  DELETE
